name: Deploy UserService to EC2 Production

on:
  pull_request:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
    - name: Set up SSH key for EC2
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEYP }}

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker images for frontend
      run: |
        docker build -t kamartinez/motivational ./motivational-service

    - name: Push images to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push kamartinez/motivational

    - name: Deploy services to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 54.145.196.198
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEYP }}
        script: |
          docker stop motivational || true
          docker rm motivational || true

          docker pull kamartinez/motivational

          docker run -d --name motivational -p 80:80 --restart unless-stopped kamartinez/motivational